### PR TITLE
Initial Module Version Commit

### PR DESCRIPTION
**Pull request by kevball2**
## Description

This is this initial version of the resource group module. 
-->

## Type of Change

- [ ] Non-module change (e.g. CI/CD, documentation, etc.)
- [ ] Azure Verified Module updates:
  - [ ] Bugfix containing backwards compatible bug fixes, and I have NOT bumped the MAJOR or MINOR version in `locals.version.tf.json`:
    - [ ] Someone has opened a bug report issue, and I have included "Closes #{bug_report_issue_number}" in the PR description.
    - [ ] The bug was found by the module author, and no one has opened an issue to report it yet.
  - [ ] Feature update backwards compatible feature updates, and I have bumped the MINOR version in `locals.version.tf.json`.
  - [ ] Breaking changes and I have bumped the MAJOR version in `locals.version.tf.json`.
  - [ ] Update to documentation

# Checklist

- [x] I'm sure there are no other open Pull Requests for the same update/change
- [x] My corresponding pipelines / checks run clean and green without any errors or warnings
- [x] I did run all  [pre-commit](https://azure.github.io/Azure-Verified-Modules/contributing/terraform/terraform-contribution-flow/#5-run-pre-commit-checks) checks

### CODE REVIEW

**Comment by JFolberth** [comment]
@mbilalamjad  adding for review as this is a new module being created. I have not published this yet.

**Comment by kevball2** [comment]
@mbilalamjad, any update on this PR?

**Comment by kevball2** [comment]
@mbilalamjad, any update on this PR?

**Comment by JFolberth** [comment]
@Azure/avm-core-team-technical-terraform looking for some assistance.

**Comment by mbilalamjad** [comment]
> @Azure/avm-core-team-technical-terraform looking for some assistance.

@JFolberth @kevball2 this is in review and will update later this week

**Comment by kevball2** [comment]
@JFolberth , @mbilalamjad  would one of you please re-run the test actions?

**Comment by kevball2** [comment]
@JFolberth , @mbilalamjad the tests require someone's approval to start

**Comment by JFolberth** [comment]
Hey @kevball2  I approved the other day and the Action is hanging. My other Terraform modules seem to be running so I will follow up internally with the team.

**Comment by segraef** [comment]
> Hey @kevball2 I approved the other day and the Action is hanging. My other Terraform modules seem to be running so I will follow up internally with the team.

Hey @JFolberth, the repo name is incorrect which results in the workflow not able to trigger the correct runner.

image

**Comment by JFolberth** [comment]
@segraef how long should we be waiting?

**Comment by segraef** [comment]
@lonegunmanb please let @JFolberth know once the runner pool was updated, thanks.

**Pull request merged**
